### ISSUE TITLE
Location of source data?

### ISSUE THREAD

**Issue by d-paulus** [rodekruis/CommunityRisk#1]
Hi, can you point to the actual location of the 4 source files mentioned in the readme? Also, what do I need to know about the secrets.json and the cert folder?

Many thanks,
David

**Comment by jannisvisser** [comment]
Hi David, 
Can you send an email to support@510.global, asking for me (Jannis)?
Thanks,
Jannis

**Comment by d-paulus** [comment]
Hi Jannis,

many thanks for the reply. Can you point to the actual location of the 4 source files mentioned in the readme (https://github.com/rodekruis/communityprofiles)? Also, what do I need to know about the secrets.json and the cert folder?

Many thanks,
David


Department of Multi Actor Systems, Policy Analysis Section
Faculty of Technology, Policy and Management

Skype: dpaulus@live.de<mailto:dpaulus@live.de>
Twitter: @_paulusd

[https://docs.google.com/uc?export=download&id=0B2qgNBes64ytbFdVUXpNTlg1bTQ&revid=0B2qgNBes64ytRzN2V1pDTDJBekJNaXpGUTlLUmdaSVhleFJvPQ]




On 19. Feb 2018, at 15:48, jannisvisser <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi David,
Can you send an email to support@510.global<mailto:support@510.global>, asking for me (Jannis)?
Thanks,
Jannis
